name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make bonus
      run: make bonus
      
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
